name: Generate Docs Website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    paths:
      - pybeepop/**
      - tests/**
      - .github/workflows/generate-docs-site.yml

permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies for docs and testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install pdoc3 pandas matplotlib
          pip install -r requirements.txt

      # Run tests and generate coverage report
      - name: Run tests and generate coverage report
        run: |
          pytest --cov=pybeepop --cov-report=term tests -v || true
          coverage report -m || true
          coverage html || true

      # Generate API documentation
      - run: pdoc --html --skip-errors -o docs/ pybeepop

      # Move coverage report into docs
      - name: Move coverage report into docs
        run: |
          mkdir -p docs/pybeepop/coverage
          cp -r htmlcov/* docs/pybeepop/coverage/

      # Create an index page that links to both docs and coverage
      - name: Create index page
        run: |
          cp docs/index_template.html docs/pybeepop/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/pybeepop/

  # Deploy the artifact to GitHub pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4